- name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Generated 2027 Analytics" || exit 0
          
          # FIX: Pull latest remote changes to sync up before pushing
          git pull --rebase origin main
          
          git push
